//
//  BluetoothManager.m
//  BLEApp
//
//  Created by Vedant Alimchandani on 12/03/24.
//

#import <Foundation/Foundation.h>

#import "BluetoothManager.h"
//#import "YourProjectName-Swift.h" // Import the autogenerated Swift header

@implementation BluetoothManager

RCT_EXPORT_MODULE();

//RCT_EXPORT_METHOD(startScan) {
//    dispatch_async(dispatch_get_main_queue(), ^{
//        BluetoothViewController *viewController = [[BluetoothViewController alloc] init];
//        [viewController startScan];
//    });
//}

@end
